module.exports = {
  apps: [
    {
      name: "twomin-core",
      cwd: "/var/www/twomin/core",
      script: "./build/server.js",
      instances: "max",
      exec_mode: "cluster",
      watch: false,
      env: {
        NODE_ENV: "production",
        DATABASE:
          "mongodb+srv://devuser:strWqSD2134CXdsr3dsWqo@dev.gyspg.mongodb.net/twomin?retryWrites=true&w=majority",
        PORT: "8090",
        LOG_DIR: "logs",
        JWT_SECRET:
          "t1s5DCwPj52SztZURFpaYwHdO6udRXQMkWNrAmVrsenrhYxB13Jn48XPrrpnxKU",
        JWT_EXPIRE: "120d",
        REDIS_HOST: "localhost",
        REDIS_PORT: 6379,
        REDIS_PASSWORD: "htgwiaAwghfb23761hYYhfbnk",
        ENABLE_NOTIFICATION: true,
        GOOGLE_GEOCODER_API_KEY: "AIzaSyBRU9o7PpgF0PVibBWtH6e9qbLbC5jpJqM",
        INTERNAL_KEY: "iMTk4MC0wMS0yNlQxMzo0OTozOC4wM",
        PUBLIC_KEY: "Mw4COzoTO0ozMxQlNy0SMw0CM4kTMi",
        TZ: "Asia/Jerusalem",
        WEBSITE_BASE_URL: "https://app.soonx.co.il",
        PAYRO_TOKEN:
          "JSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY3MTcwNzY5OCwiaWF0IjoxNjcxN",
      },
      max_memory_restart: "1024M",
      node_args: ["--max_old_space_size=10240"],
    },
    {
      name: "twomin-frontend",
      cwd: "/var/www/twomin/frontend",
      script: "node_modules/next/dist/bin/next",
      args: "start -p 8084 ./",
      instances: "max",
      exec_mode: "cluster",
      watch: false,
      env: {
        BACKEND_BASE_URL: "https://api-app.soonx.co.il/api/",
        NEXT_PUBLIC_BACKEND_BASE_URL: "https://api-app.soonx.co.il/api/",
        GOOGLE_MAP_API: "AIzaSyDnzPklWU6sYxTHadhqxqxkyFV6DJSZl58",
      },
      max_memory_restart: "512M",
      node_args: ["--max_old_space_size=5120"],
    },
    {
      name: "twomin-consumer",
      cwd: "/var/www/twomin/consumer",
      script: "./build/index.js",
      watch: false,
      env: {
        NODE_ENV: "production",
        NODE_MAILER_EMAIL: "twomin.noreplay@gmail.com",
        NODE_MAILER_PASSWORD: "kojwxqnxqxyjnbbu",
        REDIS_HOST: "localhost",
        REDIS_PORT: 6379,
        REDIS_PASSWORD: "htgwiaAwghfb23761hYYhfbnk",
        LOG_DIR: "logs",
        EXPO_ACCESS_TOKEN: "token",
        SMS_TOKEN:
          "dHdvbWluOmYwODdjZDEwLWM4MzAtNDFiMi04NGJlLTBiZjIwMTY4YTlhNw==",
        INTERNAL_KEY: "iMTk4MC0wMS0yNlQxMzo0OTozOC4wM",
        INTERNAL_BASE_URL: "https://api-app.soonx.co.il/internal",
        WEBSITE_LOGIN_URL: "https://app.soonx.co.il/login",
      },
      max_memory_restart: "512M",
      node_args: ["--max_old_space_size=5120"],
    },
  ],
};
